version: '3.4'

services:
  mydb:
    image: 'mongo'
    ports:
      - 27017:27017
  mongodb:
    image: ${DOCKER_REGISTRY-}mongodb
    build:
      context: .
      dockerfile: MongoDb.Application/Dockerfile
    environment:
      - "MongoConnection__ConnectionString=mongodb://mydb:27017"
      - "MongoConnection__DatabaseName=BookstoreDb"
    ports:
      - "5000:5000"
      - "5001:5001"
